### ISSUE TITLE
Angular Checklist down?

### ISSUE THREAD

**Issue by GregorBiswanger** [typebytes/angular-checklist#114]
Hello, 

I'm totally surprised that the website is down. Will the project continue?

**Comment by ekalashnikov-fadv** [comment]
This site was very useful. If it's possible, deploy it again please, I can donate a bit :D

**Comment by geromegrignon** [comment]
Hi @ekalashnikov-fadv, we are working on it! Dusting off the project and it'll be back soon 🚀
