### ISSUE TITLE
Content: Use modules to define features

### ISSUE THREAD

**Issue by billyjov** [typebytes/angular-checklist#36]
A common mistake is to create an app with a long list of components instead of group these into **feature modules**.

What about add this item to **architecture** category?

**Comment by KwintenP** [comment]
That seems to be the correct category to me. 
That would indeed be a nice addition!

**Comment by d3lm** [comment]
@billyjov Would you like to send a PR for this addition? I like it and I think this should be part of the list, as least as long as modules are the way to go! This will probably be the case for a while until modules eventually disappear. But first they will be optional.

**Comment by billyjov** [comment]
Yeah. I Will look at this

**Comment by billyjov** [comment]
Closes with PR #50
