### ISSUE TITLE
Validity of recommendations in checklist items

### ISSUE THREAD

**Issue by atiris** [typebytes/angular-checklist#53]
_This is a question_

Hi, are all articles listed on the site current and valid for the latest version of Angular?  
I see that some recommendations are based on articles more than 2 years old (so more than 4 versions of Angular). Wouldn't it be possible to add to the recommendations to what version of Angular is this rule applicable? Like for example: `Recommended for Angular versions 5 - latest`. And consequently only specific versions of the Angular could be filtered out in the menu.

**Comment by billyjov** [comment]
Hi,

Thank for the advice .
I Think the most checklist points are based on recent version of Angular, rxjs and ngrx.
The fact that articles are older does not mean that the content is not usefull for the recent version of Angular.  Naturally _without claim of completeness_.

**Comment by atiris** [comment]
Sure, I agree. I just miss the article creation day (if it was older, I know, that I have to verify it, or read more against actual Angular version) or what version of Angular was tested to this recommendations.  
Thanks for the quick response, feel free to close this request as resolved.

**Comment by d3lm** [comment]
The Angular checklist should be generic enough to target any Angular version >= 2. @atiris If you find something that is outdated then please open an issue and maybe even send a PR to fix it. This is a community project and we would appreciate any help from the community.

I also agree with @billyjov. If an article is old it doesn't mean that it's not applicable anymore.

But as I said. Our goal is to keep it up-to-date and if something is not considered a best practice anymore, we should definitely update the item.

**Comment by d3lm** [comment]
Is there some actionable task for this issue @atiris? Anything you'd like to see changed? Otherwise I would close this issue.

**Comment by atiris** [comment]
Thanks for check @d3lm .. Unfortunately, I don't remember why I asked exactly that. :rofl:   
Probably I meant that some recommendations are valid for specific Angular versions while for later versions (eg after the switch to IVY the recommendation may be different, but the original recommendation is still valid specific Angular version). But I see that you clearly want to adapt content only to the latest versions, so this requirement is irrelevant. :wink:   
For now I have nothing to change in actual content. Thanks.
