### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by MichaelHancock** [typebytes/angular-checklist#67]
It looks like the [site](https://angular-checklist.io/) might be down, are you aware of this? Do you know when it might be back?

**Comment by KwintenP** [comment]
Thanks for letting us know!

There was an issue with the DNS name, it should be fixed now. Prolly takes a couple of hours to propagate through. I'll ping this issue when it's back online!

**Comment by KwintenP** [comment]
Back online!

**Comment by MichaelHancock** [comment]
Thanks Kwinten
