### ISSUE TITLE
Dead link on 'Components |  put init logic in the ngOnInit lifecycle hook'

### ISSUE THREAD

**Issue by rystan** [typebytes/angular-checklist#73]
dead resource link:
* https://blog.angularindepth.com/the-essential-difference-between-constructor-and-ngoninit-in-angular-c9930c209a42

Good link: 
* https://indepth.dev/the-essential-difference-between-constructor-and-ngoninit-in-angular/

**Comment by eduardoRoth** [comment]
Fixed with #83. Issue needs to be closed.
